import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Button from '../components/Button'
export default function Home() {
  const handleOnClick = () => {
    console.log('clicked')
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <div className={styles.container}>

          <h1 className={styles.BigTitle}>Your AI Homework Assistant</h1>

          <p className={styles.TagLine}>With HomeWork Robot, get instant answers to questions or writing prompts</p>

          <Button Text='Get Started' onClick={handleOnClick} />

          {/* demo gif */}
          <div className={styles.Gif}><Image src={require('../public/demo.gif')} alt="gif" />
          </div>

        </div>

      </>
    </div>
  )
}
